// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsProcessing() {
  return window['go']['main']['App']['IsProcessing']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ResolveDrop(arg1) {
  return window['go']['main']['App']['ResolveDrop'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectInputDir() {
  return window['go']['main']['App']['SelectInputDir']();
}

export function SelectInputFiles() {
  return window['go']['main']['App']['SelectInputFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function StartProcessing(arg1) {
  return window['go']['main']['App']['StartProcessing'](arg1);
}

export function StartProcessingBatch(arg1) {
  return window['go']['main']['App']['StartProcessingBatch'](arg1);
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}
