// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function IsProcessing():Promise<boolean>;

export function ListFiles(arg1:Array<string>):Promise<Array<string>>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectInputDir():Promise<string>;

export function SelectInputFiles():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;

export function StartProcessing(arg1:string):Promise<void>;

export function StartProcessingBatch(arg1:Array<string>):Promise<void>;

export function StopProcessing():Promise<void>;
